## El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.5543852 , 0.2442935 , 0.6687153 ],
       [0.09882574, 0.11234127, 0.98143333],
       [0.70931136, 0.29004517, 0.61932864],
       [0.21834609, 0.60883127, 0.65516794],
       [0.34182868, 0.67523271, 0.89210549],
       [0.79178935, 0.11323041, 0.72701202],
       [0.38407312, 0.98156127, 0.85245881],
       [0.77465888, 0.03654088, 0.40269828],
       [0.98385901, 0.22309244, 0.03912795],
       [0.76964817, 0.49330309, 0.92564737],
       [0.10941298, 0.83709907, 0.10300157],
       [0.55921746, 0.65477216, 0.35024943],
       [0.03659786, 0.72135293, 0.13246701],
       [0.20742348, 0.21990139, 0.5024061 ],
       [0.12403229, 0.96841008, 0.52305107],
       [0.88741216, 0.72553446, 0.85204242],
       [0.74231906, 0.11914433, 0.0132812 ],
       [0.60683384, 0.09433479, 0.70930677],
       [0.03157864, 0.98814987, 0.73154417],
       [0.7407727 , 0.21185436, 0.13565777],
       [0.4747328 , 0.70689587, 0.18384704],
       [0.564598  , 0.11898188, 0.5714764 ],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.93021456, 0.0846454 , 0.65439551],
       [0.76964817, 0.49330309, 0.92564737]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1]),
 array([0.40858327, 0.7734641 , 0.30367248, 0.62485187, 0.46610403,
        0.15890815, 0.62643494, 0.29977176, 0.63292929, 0.        ,
        1.10943783, 0.63358988, 1.10385895, 0.75088076, 0.89701187,
        0.27058725, 0.66897119, 0.32815274, 0.90955814, 0.56670908,
        0.82635627, 0.37647051, 0.5818262 , 0.61111012, 0.57624386,
        0.07896183, 0.3294392 , 0.        , 0.17418877, 0.69620501]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.72671685, 0.1667654 , 0.48872929],
        [0.33162469, 0.6161273 , 0.65617267]]),
 0.37660080600216334)

In [8]:
kmeans(data,2)

(array([[0.62287199, 0.2370285 , 0.62398524],
        [0.25957079, 0.78072133, 0.52910363]]),
 0.36636177387770125)